### ISSUE TITLE
search_input form HTML errors

### ISSUE THREAD

**Issue by hcgtv** [philwareham/hive-framework#5]
Using Nu Html Checker: https://validator.w3.org/nu/

Gives me this:
Error: Attribute autosave not allowed on element input at this point.
From line 193, column 13; to line 193, column 103
<input name="q" type="search" autosave="saved-searches" results="5" itemprop="query-input">

And this:
Error: Attribute results not allowed on element input at this point.
From line 193, column 13; to line 193, column 103
<input name="q" type="search" autosave="saved-searches" results="5" itemprop="query-input">

This is a test site using the latest Textpattern master branch.

**Comment by philwareham** [comment]
Hmmm, seems to be some confusion over whether `autosave` is a standards compliant attribute or not https://developer.mozilla.org/en/docs/Web/HTML/Element/Input

The `results` attribute seems to be non-standard now (WebKit only).

Gotta love the HTML5 spec. Changes weekly.

**Comment by philwareham** [comment]
Looks like autosave is not a standards compliant attribute (MDN document is incorrect). Will remove.

**Comment by philwareham** [comment]
Fixed - thanks Bert!
